#### general settings
name: neurop_test_dark
is_pretrain: false
is_train: false
device: cpu ### "cpu|cuda"
weights: ../experiments/pretrained_models/neurop_fivek_dark.pth

#### datasets
datasets:
  name: mit_dark
  mode: finetune
  dataroot: dataset-dark
  n_cpus: 1
  batch_size: 1

#### network structures
network_G:
  pretrain_model: ~ 
  in_nc: 3
  out_nc: 3
  base_nf: 64
  cond_nf: 32
  strict_load: true